### ISSUE TITLE
history.txtについて

### ISSUE THREAD

**Issue by isso0424** [kosen19s/19s_Bot_create_by_Syulis#1]
history.txt見た感じチャットログのテキストだけどこれgit hubにpushしておくのまずくない?

**Comment by kyou-today** [comment]
保持しとく必要あるのか…？
あるんだったら.gitignoreしといて

**Comment by Syulis** [comment]
消しますた
個別にpushできるからそれでやる

**Comment by kyou-today** [comment]
solved.
